### PR TITLE
Added steps to contribute to this project

### PR DESCRIPTION
**Pull request by ManoBharathi93**
Kindly check the contribution.md and if it's okay and understandable  merge it. 
If any help kindly contact me. Happy to help you !😇

### CODE REVIEW

**Comment by itskdhere** [comment]
@ManoBharathi93 Thanks for the PR 😀
But the file name is probably wrong. It should be `CONTRIBUTING.md` instead of  `Contribution.md`.

Also, It'll be better if you can add some emojis to it like [README.md](https://github.com/itskdhere/ChatGPT-Discord-BOT/blob/main/README.md) or [LEARN.md](https://github.com/itskdhere/ChatGPT-Discord-BOT/blob/main/LEARN.md)

**Review by ManoBharathi93 — COMMENTED** [review]
Review and Approve it..

**Comment by itskdhere** [comment]
@ManoBharathi93 🤦‍♂️

File name should be ,
```
CONTRIBUTING.md
```

**Comment by itskdhere** [comment]
@ManoBharathi93 LOL

**Comment by itskdhere** [comment]
@ManoBharathi93 the file name is wrong. It should be `CONTRIBUTING.md` 
Neither `Contribution.md` nor `Contribution.md.`

Copy the actual filename:
```
CONTRIBUTING.md
```

**Review by ManoBharathi93 — COMMENTED** [review]
As per your wish I have changed. Initially I don't understand properly and sorry for the delay @itskdhere

**Comment by itskdhere** [comment]
@ManoBharathi93 Thank you for the contribution 🙏

**Pull request merged**
